
The following have been reloaded with a version change:
  1) python/3.8 => python/3.9

2021-11-17 11:23:36.609314: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1
/home/machaudr/research/stats_nn/spatial_statistics/some_file_1.py:75: RuntimeWarning: invalid value encountered in multiply
  matern_covariance = first_term * second_term * third_term
/home/machaudr/research/stats_nn/spatial_statistics/some_file_1.py:75: RuntimeWarning: invalid value encountered in multiply
  matern_covariance = first_term * second_term * third_term
/home/machaudr/research/stats_nn/spatial_statistics/some_file_1.py:75: RuntimeWarning: invalid value encountered in multiply
  matern_covariance = first_term * second_term * third_term
2021-11-17 11:23:45.877274: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-11-17 11:23:45.880631: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcuda.so.1
2021-11-17 11:23:45.910188: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties: 
pciBusID: 0000:87:00.0 name: Tesla P100-PCIE-16GB computeCapability: 6.0
coreClock: 1.3285GHz coreCount: 56 deviceMemorySize: 15.90GiB deviceMemoryBandwidth: 681.88GiB/s
2021-11-17 11:23:45.910218: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1
2021-11-17 11:23:45.914284: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublas.so.10
2021-11-17 11:23:45.914322: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublasLt.so.10
2021-11-17 11:23:45.917307: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcufft.so.10
2021-11-17 11:23:45.919173: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcurand.so.10
2021-11-17 11:23:45.922532: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusolver.so.10
2021-11-17 11:23:45.925359: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusparse.so.10
2021-11-17 11:23:45.933088: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudnn.so.7
2021-11-17 11:23:45.934841: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1862] Adding visible gpu devices: 0
2021-11-17 11:23:45.935258: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-11-17 11:23:45.936237: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties: 
pciBusID: 0000:87:00.0 name: Tesla P100-PCIE-16GB computeCapability: 6.0
coreClock: 1.3285GHz coreCount: 56 deviceMemorySize: 15.90GiB deviceMemoryBandwidth: 681.88GiB/s
2021-11-17 11:23:45.936259: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1
2021-11-17 11:23:45.936280: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublas.so.10
2021-11-17 11:23:45.936299: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublasLt.so.10
2021-11-17 11:23:45.936318: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcufft.so.10
2021-11-17 11:23:45.936336: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcurand.so.10
2021-11-17 11:23:45.936354: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusolver.so.10
2021-11-17 11:23:45.936376: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusparse.so.10
2021-11-17 11:23:45.936394: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudnn.so.7
2021-11-17 11:23:45.938076: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1862] Adding visible gpu devices: 0
2021-11-17 11:23:45.938109: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1
2021-11-17 11:23:46.501462: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1261] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-11-17 11:23:46.501511: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1267]      0 
2021-11-17 11:23:46.501523: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1280] 0:   N 
2021-11-17 11:23:46.504362: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1406] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 14957 MB memory) -> physical GPU (device: 0, name: Tesla P100-PCIE-16GB, pci bus id: 0000:87:00.0, compute capability: 6.0)
2021-11-17 11:23:46.504650: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
/home/machaudr/research/stats_nn/spatial_statistics/some_file_1.py:75: RuntimeWarning: invalid value encountered in multiply
  matern_covariance = first_term * second_term * third_term
/home/machaudr/research/stats_nn/spatial_statistics/some_file_1.py:75: RuntimeWarning: invalid value encountered in multiply
  matern_covariance = first_term * second_term * third_term
/home/machaudr/research/stats_nn/spatial_statistics/some_file_1.py:75: RuntimeWarning: invalid value encountered in multiply
  matern_covariance = first_term * second_term * third_term
/home/machaudr/research/stats_nn/spatial_statistics/some_file_1.py:75: RuntimeWarning: invalid value encountered in multiply
  matern_covariance = first_term * second_term * third_term
2021-11-17 11:23:46.918290: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:116] None of the MLIR optimization passes are enabled (registered 2)
2021-11-17 11:23:46.918833: I tensorflow/core/platform/profile_utils/cpu_utils.cc:112] CPU Frequency: 2394360000 Hz
2021-11-17 11:23:47.395582: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublas.so.10
2021-11-17 11:23:47.563223: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudnn.so.7

Testing data is being generated


Testing data has been generated


This is the start of epoch: 0


Training data is being generated


Training data has been generated
Epoch 1/2
1/2 [==============>...............] - ETA: 1s - loss: 0.2739 - root_mean_squared_error: 0.32922/2 [==============================] - 2s 3ms/step - loss: 0.5228 - root_mean_squared_error: 0.6830
Epoch 2/2
1/2 [==============>...............] - ETA: 0s - loss: 0.5953 - root_mean_squared_error: 0.81742/2 [==============================] - 0s 2ms/step - loss: 0.5887 - root_mean_squared_error: 0.7824
/home/machaudr/research/stats_nn/spatial_statistics/some_file_1.py:75: RuntimeWarning: invalid value encountered in multiply
  matern_covariance = first_term * second_term * third_term
/home/machaudr/research/stats_nn/spatial_statistics/some_file_1.py:75: RuntimeWarning: invalid value encountered in multiply
  matern_covariance = first_term * second_term * third_term
/home/machaudr/research/stats_nn/spatial_statistics/some_file_1.py:75: RuntimeWarning: invalid value encountered in multiply
  matern_covariance = first_term * second_term * third_term
/home/machaudr/research/stats_nn/spatial_statistics/some_file_1.py:75: RuntimeWarning: invalid value encountered in multiply
  matern_covariance = first_term * second_term * third_term

This is the end of epoch: 0


This is the start of epoch: 1


Training data is being generated


Training data has been generated
Epoch 1/2
1/2 [==============>...............] - ETA: 0s - loss: 0.4399 - root_mean_squared_error: 0.54402/2 [==============================] - 0s 2ms/step - loss: 0.4635 - root_mean_squared_error: 0.5683
Epoch 2/2
1/2 [==============>...............] - ETA: 0s - loss: 0.2958 - root_mean_squared_error: 0.41442/2 [==============================] - 0s 2ms/step - loss: 0.4066 - root_mean_squared_error: 0.4906
2021-11-17 11:23:48.855454: W tensorflow/python/util/util.cc:348] Sets are not currently considered sequences, but this may change in the future, so consider avoiding using them.
/home/machaudr/research/stats_nn/spatial_statistics/some_file_1.py:75: RuntimeWarning: invalid value encountered in multiply
  matern_covariance = first_term * second_term * third_term
/home/machaudr/research/stats_nn/spatial_statistics/some_file_1.py:75: RuntimeWarning: invalid value encountered in multiply
  matern_covariance = first_term * second_term * third_term
/home/machaudr/research/stats_nn/spatial_statistics/some_file_1.py:234: RuntimeWarning: divide by zero encountered in log
  log_determinant_term = 2.0 * np.trace(np.log(lower_cholesky))
/home/machaudr/research/stats_nn/spatial_statistics/some_file_1.py:75: RuntimeWarning: invalid value encountered in multiply
  matern_covariance = first_term * second_term * third_term
/home/machaudr/research/stats_nn/spatial_statistics/some_file_1.py:234: RuntimeWarning: divide by zero encountered in log
  log_determinant_term = 2.0 * np.trace(np.log(lower_cholesky))
