
The following have been reloaded with a version change:
  1) python/3.8 => python/3.9

2021-11-17 11:30:56.870692: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1
/home/machaudr/research/stats_nn/spatial_statistics/some_file_1.py:75: RuntimeWarning: invalid value encountered in multiply
  matern_covariance = first_term * second_term * third_term
/home/machaudr/research/stats_nn/spatial_statistics/some_file_1.py:75: RuntimeWarning: invalid value encountered in multiply
  matern_covariance = first_term * second_term * third_term
/home/machaudr/research/stats_nn/spatial_statistics/some_file_1.py:75: RuntimeWarning: invalid value encountered in multiply
  matern_covariance = first_term * second_term * third_term
2021-11-17 11:31:04.672665: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-11-17 11:31:04.697139: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcuda.so.1
2021-11-17 11:31:04.777673: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties: 
pciBusID: 0000:0d:00.0 name: Tesla V100-PCIE-16GB computeCapability: 7.0
coreClock: 1.38GHz coreCount: 80 deviceMemorySize: 15.78GiB deviceMemoryBandwidth: 836.37GiB/s
2021-11-17 11:31:04.777719: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1
2021-11-17 11:31:04.839981: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublas.so.10
2021-11-17 11:31:04.840104: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublasLt.so.10
2021-11-17 11:31:04.989204: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcufft.so.10
2021-11-17 11:31:05.071940: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcurand.so.10
2021-11-17 11:31:05.141115: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusolver.so.10
2021-11-17 11:31:05.204578: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusparse.so.10
2021-11-17 11:31:05.388744: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudnn.so.7
2021-11-17 11:31:05.392742: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1862] Adding visible gpu devices: 0
2021-11-17 11:31:05.393227: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-11-17 11:31:05.396535: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties: 
pciBusID: 0000:0d:00.0 name: Tesla V100-PCIE-16GB computeCapability: 7.0
coreClock: 1.38GHz coreCount: 80 deviceMemorySize: 15.78GiB deviceMemoryBandwidth: 836.37GiB/s
2021-11-17 11:31:05.396569: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1
2021-11-17 11:31:05.396609: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublas.so.10
2021-11-17 11:31:05.396644: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublasLt.so.10
2021-11-17 11:31:05.396662: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcufft.so.10
2021-11-17 11:31:05.396680: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcurand.so.10
2021-11-17 11:31:05.396697: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusolver.so.10
2021-11-17 11:31:05.396723: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusparse.so.10
2021-11-17 11:31:05.396742: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudnn.so.7
2021-11-17 11:31:05.399794: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1862] Adding visible gpu devices: 0
2021-11-17 11:31:05.399829: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1
2021-11-17 11:31:06.737913: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1261] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-11-17 11:31:06.737967: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1267]      0 
2021-11-17 11:31:06.737981: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1280] 0:   N 
2021-11-17 11:31:06.743993: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1406] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 14761 MB memory) -> physical GPU (device: 0, name: Tesla V100-PCIE-16GB, pci bus id: 0000:0d:00.0, compute capability: 7.0)
2021-11-17 11:31:06.744340: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
/home/machaudr/research/stats_nn/spatial_statistics/some_file_1.py:75: RuntimeWarning: invalid value encountered in multiply
  matern_covariance = first_term * second_term * third_term
/home/machaudr/research/stats_nn/spatial_statistics/some_file_1.py:75: RuntimeWarning: invalid value encountered in multiply
  matern_covariance = first_term * second_term * third_term
/home/machaudr/research/stats_nn/spatial_statistics/some_file_1.py:75: RuntimeWarning: invalid value encountered in multiply
  matern_covariance = first_term * second_term * third_term
/home/machaudr/research/stats_nn/spatial_statistics/some_file_1.py:75: RuntimeWarning: invalid value encountered in multiply
  matern_covariance = first_term * second_term * third_term
2021-11-17 11:31:07.211698: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:116] None of the MLIR optimization passes are enabled (registered 2)
2021-11-17 11:31:07.212321: I tensorflow/core/platform/profile_utils/cpu_utils.cc:112] CPU Frequency: 2394515000 Hz
2021-11-17 11:31:07.761639: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublas.so.10
2021-11-17 11:31:08.057374: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudnn.so.7

Testing data is being generated


Testing data has been generated


This is the start of epoch: 0


Training data is being generated


Training data has been generated
Epoch 1/2
1/2 [==============>...............] - ETA: 2s - loss: 0.7695 - root_mean_squared_error: 0.93002/2 [==============================] - 3s 4ms/step - loss: 0.7628 - root_mean_squared_error: 0.9263
Epoch 2/2
1/2 [==============>...............] - ETA: 0s - loss: 0.6512 - root_mean_squared_error: 0.83162/2 [==============================] - 0s 2ms/step - loss: 0.6470 - root_mean_squared_error: 0.8366
/home/machaudr/research/stats_nn/spatial_statistics/some_file_1.py:75: RuntimeWarning: invalid value encountered in multiply
  matern_covariance = first_term * second_term * third_term
/home/machaudr/research/stats_nn/spatial_statistics/some_file_1.py:75: RuntimeWarning: invalid value encountered in multiply
  matern_covariance = first_term * second_term * third_term
/home/machaudr/research/stats_nn/spatial_statistics/some_file_1.py:75: RuntimeWarning: invalid value encountered in multiply
  matern_covariance = first_term * second_term * third_term
/home/machaudr/research/stats_nn/spatial_statistics/some_file_1.py:75: RuntimeWarning: invalid value encountered in multiply
  matern_covariance = first_term * second_term * third_term

This is the end of epoch: 0


This is the start of epoch: 1


Training data is being generated


Training data has been generated
Epoch 1/2
1/2 [==============>...............] - ETA: 0s - loss: 0.3751 - root_mean_squared_error: 0.42602/2 [==============================] - 0s 2ms/step - loss: 0.3463 - root_mean_squared_error: 0.4037
Epoch 2/2
1/2 [==============>...............] - ETA: 0s - loss: 0.2662 - root_mean_squared_error: 0.28032/2 [==============================] - 0s 2ms/step - loss: 0.2525 - root_mean_squared_error: 0.2650
2021-11-17 11:31:10.549471: W tensorflow/python/util/util.cc:348] Sets are not currently considered sequences, but this may change in the future, so consider avoiding using them.
/home/machaudr/research/stats_nn/spatial_statistics/some_file_1.py:75: RuntimeWarning: invalid value encountered in multiply
  matern_covariance = first_term * second_term * third_term
/home/machaudr/research/stats_nn/spatial_statistics/some_file_1.py:75: RuntimeWarning: invalid value encountered in multiply
  matern_covariance = first_term * second_term * third_term
/home/machaudr/research/stats_nn/spatial_statistics/some_file_1.py:234: RuntimeWarning: divide by zero encountered in log
  log_determinant_term = 2.0 * np.trace(np.log(lower_cholesky))
